name: Code coverage backend-client
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python 3.9
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        export PYTHONPATH=API-BACKEND-CLIENT/api
        pytest --cov=API-BACKEND-CLIENT/api --cov-report=xml