name: Code coverage backend-client
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python 3.9
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Replace path in yml for creating log file and creating folder (missing permissions in workflow)
      run: |
        sed -i "s|/home/pi/|/home/runner/work/MRAS-CLIENT-NIC/|g" config.yml
        mkdir /home/runner/work/MRAS-CLIENT-NIC/logs
    - name: Replace logging to remote address with mock server
      run: |
        sed -i "s|\"http://\" + ip + \"/log\"|\"http://ad21d7ee-c4d7-4dc2-8b0c-35b2083b27c5.mock.pstmn.io/log\"|g" API/logger.py
    - name: Run Tests
      run: |
        export PYTHONPATH=API
        pytest --cov=API --cov-report=xml
    - name: Change dir path for sonarqube
      run: | 
        sed -i "s|/home/runner/work/MRAS-CLIENT-NIC/MRAS-CLIENT-NIC/||g" coverage.xml
        echo $(less coverage.xml | grep /github/workspace/)
    - name: Copy to code coverage folder
      run: |
        mkdir coverage-reports
        mv coverage.xml coverage-reports/coverage-api.xml
    - name: Sonarqube scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: ${{ secrets.SONAR_HOST }}
        login: ${{ secrets.SONAR_TOKEN }}