name: Code coverage backend-client
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python 3.9
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        export PYTHONPATH=API-BACKEND-CLIENT/api
        pytest --cov=API-BACKEND-CLIENT/api --cov-report=xml
    - name: Copy to code coverage folder and push to repo
      run: |
        if test -f coverage-reports/coverage.xml; then
          if cmp -s coverage.xml coverage-reports/coverage.xml; then
            mv coverage.xml coverage-reports/
            git config --global user.name "Nicolas"
            git config --global user.email "nicolas@schuessling.com"
            git add coverage-reports/coverage.xml -f
            git commit -m "Automatically added code coverage"
            git push
          fi
        else
          mkdir coverage-reports
          mv coverage.xml coverage-reports/
            git config --global user.name "Nicolas"
            git config --global user.email "nicolas@schuessling.com"
            git add coverage-reports/coverage.xml -f
            git commit -m "Automatically added code coverage"
            git push
        fi