name: "release"
on: 
  workflow_run:
    workflows:
      - Code coverage backend-client
    types:
      - completed
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@master
      - name: "remove tests and zip"
        run: |
          cd /home/runner/work/MRAS-CLIENT-NIC/MRAS-CLIENT-NIC
          rm -rf API/tests/
          tar -zcvf api.tar.gz API/ 
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Backend API Release"
          files: |
            *.tar.gz