# This is a basic workflow to help you get started with Actions

name: Sonarqube code inspection

# Controls when the action will run. 
on: 
  workflow_run:
    workflows: ["Code coverage backend-client"]
    types:
      - completed
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: ${{ secrets.SONAR_HOST }}
        login: ${{ secrets.SONAR_TOKEN }}
